"""Intent triage: is a message a TASK (something to DO), a quick REPLY_ONLY question, or
FYI noise? Heuristic by default; pass any `llm(system, user) -> str-json` callable to
upgrade (provider-agnostic - wire your own OpenAI/Anthropic/local call in config).
"""
import json, re
import re as _re

# What each verdict COSTS is part of the judgement, so it is in the prompt: a task starts a
# real agent in a real repo; a reply is one cheap draft the owner approves. Defaulting to
# "task" turned questions into background work nobody asked for.
# `kind` costs something too, and this is the ONE place that decides it: coding starts a
# session, general opens a non-coding conversation, and task leaves the job on the owner's list.
# Nothing downstream re-reads the mail
# to second-guess it - no keyword, sender or category rule anywhere else (owner, 2026-08-30,
# after a training reminder got a coder run: the exception is "clearly not a coding job",
# and it is judged here, in a document that can be argued with).
# This text also ships as templates/triage.md - the editable TRIAGE.md doc that overrides it
# (see classify_intent's `system` param). It stays here too as the fallback for a blanked doc.

# The evidence fields the payload carries, each with what it CONTAINS - a data dictionary, never a judgement. How
# much each one counts for is TRIAGE.md's to say (templates/triage.md, "The evidence you may be given"); this is
# only appended for a field an owner-written document never names, so the model is not handed an unexplained key.
# (The judgement that used to live here - "prefer fyi", "this is fyi" - moved to the document 2026-10-09: the owner
# asked why triage still had rules in code, and the answer was that nobody had moved them.)
FIELDS = {
    'others_replied': "others_replied names people other than the owner and the sender who have SENT a message on this thread; "
                      "last_on_thread is whoever spoke most recently.",
    'exchange': "exchange is the recent back-and-forth on this thread or chat room, oldest first, each message's own words once, "
                "the owner's lines marked \"you\".",
    'idea_context': "idea_context means this item was GENERATED by the Advisor (the report that reviews everything and raises ideas), "
                    "not sent by a person: the report it came from, the task it names (with its status) and whether a worker has it.",
    'sender_history': "sender_history is how this sender's last few asks were worked, newest first: each one's kind and repository.",
    'recently_closed': "recently_closed is work on this thread, sender or subject that was closed in the last few days, each with its "
                       "tid and how it ended - the finding the agent wrote, or the ask if no agent ran.",
    'open_work': "open_work is the OPEN tasks this message touches, each with its tid.",
    'assistant_said': "assistant_said is what the Advisor already raised about this thread and what the owner did with it.",
}

# WHAT THE ANSWER MUST CONTAIN, as opposed to what the verdict should BE. Named separately
# because an owner-written or generated TRIAGE.md REPLACES INTENT_SYSTEM wholesale, and this
# install's (UpdatedBy=histgen) never mentions title, summary or checklist - so the model
# answered intent/kind/why only, ingest fell back to routing.draft_task_fields' body[:1000],
# and every task carried the whole email as its ask, signature and legal footer included, with
# no todos at all (the owner, 2026-09-10). classify_intent re-appends this when the document
# omits it, for exactly the reason it re-appends FIELDS: the output SHAPE is a contract, not a
# judgement, and the document is only entitled to the judgement.
#
# A REPLY LANDS AS A ROW TOO. This said "for a task", and reply_only is a different intent - so a
# question triage decided to answer came back as intent/why alone, took the same fallback, and put
# Maya's whole mail on the card: her one sentence, her signature, the legal notice and the thread
# under it, 5,998 characters of it (the owner, 2026-09-14). Answering for a reply as well costs a
# title and two sentences on a call already being made, and it is the same question the model has
# just answered for itself in `why`. The checklist stays the task's: what a reply owes is the reply.
_AT_ORG = re.compile(r'\s+at\s+[^,<>@]+$', re.I)


def person_name(name) -> str:
    """A display name as a person is called: "Doyle, Alex M. at Northwind" -> "Alex M. Doyle". Outlook's directory writes
    "Last, First" and appends " at <organisation>" to people outside it; a name with an @ is an address, not a name."""
    n = ' '.join(str(name or '').replace('"', ' ').split())
    if not n or '@' in n: return ''
    n = _AT_ORG.sub('', n).strip()
    if n.count(',') == 1:
        last, first = (x.strip() for x in n.split(','))
        if last and first and len(last.split()) <= 2: n = f'{first} {last}'
    return n


# THE SHIPPED GUIDE IS ONE TEXT: templates/triage.md. It is what a blanked TRIAGE.md falls back to, and the source of
# the few parts appended to an owner-written document that never mentions them (the answer's shape, urgent, due) -
# so a wording lives in one place and every reader of it reads the same words.
from pathlib import Path as _Path
SHIPPED = re.sub(r'<!--.*?-->', '', (_Path(__file__).parent / 'templates' / 'triage.md').read_text(encoding='utf-8'), flags=re.S).strip()


def shipped_section(head: str) -> str:
    """The template's section whose heading starts with `head` ("## 5."), heading included - '' when there is none."""
    m = re.search(rf'^{re.escape(head)}.*?(?=^## |\Z)', SHIPPED, re.M | re.S)
    return m.group(0).strip() if m else ''


def _bullet(name: str) -> str:
    m = re.search(rf'^- \*\*{name}\*\*.*$', SHIPPED, re.M)
    return m.group(0) if m else ''


# WHAT THE ANSWER MUST CONTAIN (title, summary, checklist...), as opposed to what the verdict should BE: appended when a
# document never asks for it, because without it every task carried the whole email as its ask (2026-09-10, TQ-0665).
TASK_FIELDS = shipped_section('## 5.') + '\n\n' + shipped_section('## 7.')
URGENT, DUE = _bullet('urgent'), _bullet('due')


def due_of(j: dict, sent=None) -> str | None:
    """The verdict's due day, only when it is a real date within a week before and a year after the mail - a model's
    invented or misread year never lands on a task."""
    from datetime import date, datetime, timedelta
    s = str((j or {}).get('due') or '').strip()[:10]
    if not re.fullmatch(r'\d{4}-\d{2}-\d{2}', s): return None
    try: d = date.fromisoformat(s)
    except ValueError: return None
    try: base = date.fromisoformat(str(sent or '')[:10])
    except ValueError: base = datetime.now().date()
    return s if base - timedelta(days=7) <= d <= base + timedelta(days=366) else None

def verdict_schema(repos=None, candidates=None, playbooks=None, profiles=None, same=False) -> dict:
    """The answer's shape as a JSON schema, for the brains whose wire can carry one (llm.ask_json).

    Prose asks; a schema binds. Handed this, gpt-5.4 answered `title` and `summary` even when the
    prompt's own contract line named neither - which is exactly the failure it exists to stop.

    Two rules shape it. Strict mode's: every property is required, so an OPTIONAL field is a
    nullable one instead, and nothing outside the list may be answered. And ours: it names only
    the fields the prompt EXPLAINED. Given a wider schema on a plain mail, the model dutifully
    filled in a `relationship` and a `repo_reason` for a thread that had neither (TQ-0665)."""
    p = {'intent': {'type': 'string', 'enum': ['task', 'reply_only', 'fyi']},
         'why': {'type': 'string'}, 'title': {'type': 'string'}, 'summary': {'type': 'string'},
         'kind': {'type': ['string', 'null'], 'enum': ['coding', 'general', 'task', None]},
         'checklist': {'type': ['array', 'null'], 'items': {'type': 'string'}}, 'urgent': {'type': 'boolean'},
         'due': {'type': ['string', 'null']},
         # what closes it beyond the reply (slots.py): emails to OTHER people the message asks the owner to send
         'outputs': {'type': ['array', 'null'], 'items': {'type': 'object', 'additionalProperties': False, 'required': ['to', 'about'],
                                                          'properties': {'to': {'type': 'string'}, 'about': {'type': 'string'}}}}}
    if playbooks: p['playbook'] = {'type': ['string', 'null']}
    if profiles: p['profile'] = {'type': ['string', 'null']}
    if repos: p.update(repository={'type': ['string', 'null']}, needs_repo_choice={'type': 'boolean'},
                       repo_reason={'type': 'string'})
    if candidates is not None:
        p.update(relationship={'type': ['string', 'null'], 'enum': ['new', 'continues', 'answers', 'uncertain', None]},
                 related_message_ids={'type': ['array', 'null'], 'items': {'type': 'integer'}},
                 existing_task_id={'type': ['integer', 'null']}, same_problem={'type': ['boolean', 'null']})
    if same: p['same_as'] = {'type': ['integer', 'null']}
    return {'name': 'triage_verdict',
            'schema': {'type': 'object', 'additionalProperties': False, 'required': list(p), 'properties': p}}


INTENT_SYSTEM = SHIPPED

def addressed_to_you(msg: dict, mine=()) -> str:
    """'to', 'cc', 'not named', or '' when the channel carries no recipient lines at all (chat) -
    the one fact that separates "this is mine" from "I am watching someone else's thread", and it
    was never collected, so no classifier could ever weigh it. The ADDRESSES are deliberately not
    returned: what reaches a prompt is the relationship, never the mailbox (0.2.1, no addresses in
    prompts)."""
    # EVERY address that is the owner, not just the mailbox this copy landed in. Mail to a
    # shared or journal mailbox is still addressed to them when their own address is on the Cc
    # line - and comparing only the arrival mailbox called that 'not named', which is exactly
    # backwards for the case the whole signal exists to catch.
    # `mine` is the owner's OWN address(es) (ingest.own_addresses). When the caller knows them,
    # the mailbox this copy arrived in is NOT added: a shared or journal mailbox Taskuary polls
    # receives everybody's mail, and counting it as "me" made every message to it read as
    # aimed at the owner (2026-08-27: a refund question to devteam-logs@ came out as 'to').
    # With no `mine` at all, the arrival mailbox is the only "me" there is.
    me = {str(a).lower() for a in mine if a} or {a for a in {(msg.get('source_name') or '').strip().lower()} if a}
    to = {str(a).lower() for a in (msg.get('to') or [])}
    cc = {str(a).lower() for a in (msg.get('cc') or [])}
    if not me or not (to or cc): return ''
    return 'to' if me & to else 'cc' if me & cc else 'not named'


_ASK = re.compile(r'\b(can you|could you|are you|do you|would you|let me know|please confirm|any update)\b', re.I)
_ACT = re.compile(r'\b(please (add|send|update|fix|remove|create|set up)|need you to|action required|please complete)\b', re.I)
_FYI = re.compile(r'\b(fyi|for your (records|reference)|no action (needed|required)|auto-?generated|this is an automated|do not reply)\b', re.I)


def heuristic_intent(msg: dict, mine=()) -> dict:
    body = (msg.get('body') or '').strip()
    low = f"{msg.get('subject') or ''} {body[:600]}"
    if _FYI.search(low) and not body.rstrip().endswith('?'):
        return {'intent': 'fyi', 'why': 'carries automated/no-action markers and asks no question (keyword heuristic)'}
    if _ACT.search(low): return {'intent': 'task', 'why': 'explicitly asks for something to be done (keyword heuristic)'}
    if body.rstrip().endswith('?') or _ASK.search(low):
        return {'intent': 'reply_only', 'why': 'reads as a question an answer settles (keyword heuristic)'}
    # A cc used to be FILED here, by keyword, before any model saw it - which is the one thing
    # the To/Cc signal must not do. Plenty of cc'd mail is genuinely yours: the sender put the
    # owner in cc and addressed them in the body, or they are the only person who can answer.
    # Deciding that from the header alone is a guess wearing a rule's clothing, so the fields
    # are handed to the classifier as evidence and the classifier decides. It costs one AI call
    # on quiet cc mail that this used to settle for free; being right is worth more.
    return {'intent': 'task', 'why': 'no fyi markers and no plain question - assumed real work (keyword heuristic, no AI read this)'}


# ── the message, minus the wrapper ──────────────────────────────────────────────────────
# Corporate mail arrives half signature: name, title, phone block, an inspirational quote,
# and a confidentiality NOTICE longer than the ask. All of it rode into every AI call - the
# triage, the seeded session, the reply drafts - spending context on boilerplate. The STORED
# body stays whole (the panel shows the real mail); only what is fed to an AI is trimmed,
# and always conservatively: when in doubt, keep.
# the heading alternative is case-SENSITIVE (or title case with a colon): a footer shouts NOTICE;
# "Notice the error at the top - can you fix it" is the ask, and a case-blind match threw it and
# everything after it away before triage ever saw it (audit 2026-09-02)
_LEGAL = _re.compile(r'^\s*(NOTICE|DISCLAIMER|CONFIDENTIALITY( NOTICE)?|LEGAL NOTICE)[:\s]'
                     r'|^\s*(Notice|Disclaimer|Confidentiality Notice|Legal Notice):'
                     r'|(?i:this (e-?mail|message|communication)[^.]{0,120}(confidential|privileged|intended (solely|only))'
                     r'|if you (are not the intended|have received this[^.]{0,40}in error)'
                     r'|unauthorized (use|review|disclosure|distribution))')
_VALEDICTION = _re.compile(r'^\s*(thank(s| you)|best( regards| wishes)?|kind(est)? regards|regards|'
                           r'sincerely|respectfully|warm(ly| regards)?|cheers|v/?r)\s*[,!.]*\s*$', _re.I)
# ...and the shapes a mail client actually writes them in: Outlook's phone dash is U+2011, and it
# pads a signature block with zero-width spaces (which str.strip() does not remove, so the block
# read as ordinary text). The \b ending the first alternative had been eaten to a literal backspace,
# so a bare 'Phone:' or 'Email:' line never matched and every signature rode into the prompt.
_DASH = '\u2010\u2011\u2012\u2013\u2014\u2212-'
_BLANKISH = _re.compile(r'^[\s\u200b\u200c\u200d\ufeff\u00a0]*$')
# ...and Outlook writes the label AFTER the number - "(540) 776-7588 Office" - which the anchored
# number pattern missed, so a signature stopped being trimmed one line early (TQ-0665)
_CONTACT = _re.compile(r'^\s*(phone|tel|mobile|cell|fax|office|direct|email|e-?mail|web|www\.|address)\b'
                       r'|^\s*\+?[\d(][\d\s().x' + _DASH + r']{6,}(\s*(office|direct|mobile|cell|fax|tel|phone|work|home))?\s*$'
                       r'|^[^@\s]+@[^@\s]+\.[a-z]{2,}\s*$', _re.I)
_KEEP_MIN = 30          # never trim a message down past this - when in doubt, keep
# the corporate wrapper AROUND a body, not the sender's words: the external-mail banner and the
# "you don't often get email" hint (one pattern for every surface - assistant.py imports it)
_BANNER = _re.compile(r"(this email was sent from outside of[^*\n]*(\*\*[^*]*\*\*)?\s*|"
                      r"\[?\s*you don'?t often get email from \S+\.?( learn why this is important( at \S+)?)?\s*\]?)", _re.I)
# footer clutter: a mail client's stamp, a newsletter's unsubscribe strip - whole lines made of these
_CLUTTER_BIT = (r"(sent from my [\w ]+|get outlook for (ios|android)|sent via [\w ]+|unsubscribe( here| from this list)?|"
                r"manage (your )?(email )?preferences|view (this )?(email )?in (your )?browser|update your preferences|opt out)")
_CLUTTER = _re.compile(r'^\s*(' + _CLUTTER_BIT + r')(\s*[|·•\-]\s*' + _CLUTTER_BIT + r')*\s*\.?\s*$', _re.I)
BODY_BUDGET = 6000      # the current body reaches the model whole up to this; a cut is disclosed, never silent
EXCHANGE_BUDGET = 12000
NL = chr(10)


def strip_banner(text: str) -> str:
    """The words to SHOW: a mail system's external-sender banner and a client's clutter lines removed,
    everything else as it arrived. triage read past these from the start, but every surface that shows a
    message - the card, the task's source list, the phone - printed them first (the owner, 2026-09-23:
    "this email etc or template of all emails ... should be removed from everywhere"). The mail as STORED
    is untouched; this is how it is read."""
    kept = NL.join(l for l in _BANNER.sub('', text or '').splitlines() if not _CLUTTER.match(l)).strip()
    return kept or (text or '')


def read_text(body: str, own: str = None) -> str:
    """What the owner READS of a message: the sender's own words this time - the mailbox's own cut when
    it gave one (Graph uniqueBody, message.OwnText), else split_own's - with the legal footer, the signature
    block and the external-sender banner gone. The same cleaning triage already reads through, now on every
    screen (the owner, 2026-09-23: "NOTICE etc ... no one needs to see it"). The mail as stored is untouched;
    a screen that shows this offers the whole email beside it."""
    t = strip_boilerplate(str(own).strip()) if own and str(own).strip() else own_words(body or '')
    return strip_banner(t) or strip_banner(body or '')


def strip_boilerplate(text: str) -> str:
    """The words the sender actually typed: the legal footer and the signature block go,
    everything before them stays byte-for-byte."""
    lines = [l for l in _BANNER.sub('', text or '').splitlines() if not _CLUTTER.match(l)]
    # 1. the legal footer: from the first legalese line to the end
    for i, l in enumerate(lines):
        if _LEGAL.search(l) and len(NL.join(lines[:i]).strip()) >= _KEEP_MIN:
            lines = lines[:i]
            break
    # 2. the signature: a closing valediction in the tail, followed by the name/title/phone block
    tail_from = max(1, len(lines) - 14)
    for i in range(len(lines) - 1, tail_from - 1, -1):
        if _VALEDICTION.match(lines[i]) and len(NL.join(lines[:i]).strip()) >= _KEEP_MIN:
            lines = lines[:i]
            break
    # 3. stray contact lines left at the very end (a block with no valediction above it)
    while lines and (_CONTACT.match(lines[-1]) or _BLANKISH.match(lines[-1])):
        if len(NL.join(lines[:-1]).strip()) < _KEEP_MIN: break
        lines.pop()
    out = NL.join(lines).rstrip()
    return out if out.strip() else (text or '')


# a quoted copy of an earlier mail inside a reply - only when its words are ALREADY in the chain
_QUOTE_HEAD = _re.compile(r'^\s*(on .{6,160} wrote:\s*$|-{2,}\s*original message\s*-{2,}|-{2,}\s*forwarded message\s*-{2,}|_{5,}\s*$)', _re.I)
_MAIL_HDR = _re.compile(r'^\s*(from|sent|to|cc|subject|date):\s', _re.I)


def _norm_line(l: str) -> str:
    """Remove quote framing without erasing case, operators or literal spacing."""
    text = _re.sub(r'^\s*(?:>\s+)+', '', str(l or ''))
    return text.strip()


def split_own(text: str, floor: int = None) -> tuple:
    """(what the sender typed THIS time, the chain they wrote it on top of).

    strip_boilerplate finds the legal footer and the signature at the END of a body. A forwarded
    mail has neither there - it has a quote head, and under it somebody else's mail with their
    signature - so Ray's one-sentence ask reached the card with 8,400 characters of chain beneath
    it, headers and both signatures included (TQ-0665, 2026-09-21). Cut at the quote first and the
    signature rules have the tail they were written for. A message with no chain is untouched, and
    nothing is ever cut down to nothing.

    The chain is RETURNED, never thrown away: a forward carries the only copy of what it forwards,
    and the caller decides whether the thread already holds it (sender_body).

    `floor` is how few characters of their own the cut may leave. own_words DROPS the chain, so it
    keeps this module's when-in-doubt-keep floor; sender_body only MOVES it under a line, where
    "Sending it today." on top of a thousand quoted lines is exactly the split worth making."""
    lines = str(text or '').splitlines()
    for i, l in enumerate(lines):
        head = (l.lstrip().startswith('>') or _QUOTE_HEAD.match(l)
                or (_re.match(r'^\s*from:\s', l, _re.I) and i + 1 < len(lines) and _re.match(r'^\s*(sent|date):\s', lines[i + 1], _re.I)))
        if head and len(NL.join(lines[:i]).strip()) >= (_KEEP_MIN if floor is None else floor):
            return strip_boilerplate(NL.join(lines[:i]).rstrip()), NL.join(lines[i:]).strip()
        # ...and Outlook's HTML often glues the quote head onto the signature's last line ("MFA Heritage From: Ashley ...",
        # "Sent:" under it): a "2:30 Thursday works." read as asking, from the "?" in the mail it quoted (2026-10-06)
        glued = _re.search(r'\sfrom:\s', l, _re.I) if i + 1 < len(lines) and _re.match(r'^\s*(sent|date):\s', lines[i + 1], _re.I) else None
        if glued and len(NL.join(lines[:i] + [l[:glued.start()]]).strip()) >= (_KEEP_MIN if floor is None else floor):
            return (strip_boilerplate(NL.join(lines[:i] + [l[:glued.start()]]).rstrip()),
                    NL.join([l[glued.start():].strip()] + lines[i + 1:]).strip())
    return (strip_boilerplate(NL.join(lines).rstrip()) if lines else strip_boilerplate(text)), ''


def own_words(text: str) -> str:
    """What the sender typed this time, without the chain under it (split_own)."""
    return split_own(text)[0]


def below(text: str, own: str) -> str:
    """The chain under `own` when the MAILBOX said where the sender's words end (Graph's uniqueBody).
    Found by the last line of `own` that the body still holds - the two come from the same mail but
    not through the same HTML - and falling back to the cut this module can find for itself."""
    last = next((l for l in reversed([l.strip() for l in str(own or '').splitlines() if l.strip()])), '')
    i = str(text or '').find(last) if len(last) >= 12 else -1
    return text[i + len(last):].strip() if i >= 0 else split_own(text, floor=1)[1]


CHAIN_HEAD = '--- quoted under it, the chain they wrote on top of (their ask is ABOVE this line)'


def sender_body(text: str, own: str = None, budget: int = None, known: set = None) -> tuple:
    """(what one message should look like to a model, whether the budget cut anything).

    The sender's own words first, the chain marked as quoted underneath, and the cut taken out of
    the CHAIN. It used to be strip_boilerplate(body)[:BODY_BUDGET] - which reads the tail of a body,
    so on a forwarded mail the ask was one sentence on top of 8,400 characters of somebody else's
    mail and the budget trimmed the wrong end (TQ-0665). `own` is the mailbox's own answer for where
    the sender's words end; `known` is the lines the thread already carries, which is the only
    reason a quoted block is ever dropped."""
    budget = BODY_BUDGET if budget is None else budget
    head, chain = split_own(text, floor=1)
    # no _KEEP_MIN floor on this one: "Please approve this today." is 26 characters and is the whole
    # ask. A mailbox answer that is short is still an answer; an EMPTY one is not, and nothing under
    # it is lost either way - what is not their words goes below the line, it does not go away.
    if str(own or '').strip() and len(str(own).strip()) < len(head):
        head, chain = strip_boilerplate(str(own).strip()), below(str(text or ''), own)
    # the chain goes through the same doors every other quoted block does: its From:/Sent:/To: header
    # lines are wrapper and always go, its words go only where `known` says the thread already has
    # them, and the signature and legal footer under somebody else's mail are boilerplate there too.
    if chain: chain = strip_boilerplate(dedupe_quoted(chain, (), known=known if known is not None else set()))
    room = budget - len(head) - len(CHAIN_HEAD) - 2
    if not chain or room < 200: return head[:budget], len(head) > budget or bool(chain)
    return f'{head}{NL}{CHAIN_HEAD}{NL}{chain[:room]}', len(chain) > room


def known_lines(bodies) -> set:
    """The normalised lines of these cleaned bodies - what dedupe_quoted treats as already said."""
    return {_norm_line(l) for p in bodies for l in str(p or '').splitlines() if _norm_line(l)}


def dedupe_quoted(body: str, priors, known: set = None) -> str:
    """Each message's own words once (PW-028). A quoted block - '> ' lines, or everything under an
    'On ... wrote:' / 'Original Message' / 'Forwarded message' head - is dropped only when its lines
    are already in `priors` (the cleaned bodies of the chain so far); unique forwarded material and
    a quote of something the chain does not hold stay, and inline answers keep their own lines with
    the quoted questions they answer removed. The stored message is never edited.

    `known` is those same lines already normalised, for a caller walking a whole chain: rebuilding
    the set from every prior body on every call normalised each line once per LATER message -
    241,491 regex calls to keep 10 lines of a 200-message conversation, 773ms before the model was
    even asked (the owner's assistant thread, 2026-09-17). The set is only ever read here."""
    if known is None: known = known_lines(priors)
    lines, out, i = str(body or '').splitlines(), [], 0
    while i < len(lines):
        l = lines[i]
        if l.lstrip().startswith('>'):
            # A run of quote-prefixed lines is one block. Dropping its familiar lines one by
            # one can splice a new instruction out of its context, so keep the whole run when
            # any substantive line is new. A single quoted question in an inline reply remains
            # removable because the sender's unquoted answer ends that run.
            quoted = []
            while i < len(lines) and lines[i].lstrip().startswith('>'):
                quoted.append(lines[i].lstrip()[1:].strip())
                i += 1
            subst = [_norm_line(x) for x in quoted if _norm_line(x)]
            if not subst or any(x not in known for x in subst): out.extend(quoted)
            continue
        head = _QUOTE_HEAD.match(l) or (_re.match(r'^\s*from:\s', l, _re.I) and i + 1 < len(lines) and _re.match(r'^\s*(sent|date):\s', lines[i + 1], _re.I))
        if head:
            rest = [x for x in lines[i + 1:] if not _MAIL_HDR.match(x)]
            subst = [_norm_line(x.lstrip('> ').strip()) for x in rest if _norm_line(x)]
            if subst and all(x in known for x in subst): break                           # an exact copy of what the chain holds
            # Mixed quoted/forwarded blocks stay whole: a familiar majority is not evidence
            # that the remaining lines are disposable. Header fields alone are still wrapper.
            out.extend(x.lstrip('> ') if x.lstrip().startswith('>') else x for x in rest); break
        out.append(l); i += 1
    return '\n'.join(out).rstrip()


# The same two sentences the full verdict is asked for, and the same checklist rule, so a task
# born by hand reads like one born from triage. Deliberately NOT a second opinion on kind,
# repository or playbook: promoting is the owner saying "this is work", and re-litigating that
# is how a hand-made task would end up somewhere they did not put it.
ASK_SYSTEM = (
    'You are reading one message that the owner has just turned into a task. Answer ONLY with a '
    'JSON object: {"summary": "<two sentences: who wants what from the owner, asker first, then the one '
    'detail that matters>", '
    '"checklist": ["<one distinct requested outcome each>"], '
    '"outputs": [{"to": "<who>", "about": "<what to tell them>"}]}. Outputs are ONLY messages it asks the owner to send to '
    'OTHER people, the address when given, else the name as written; [] when none. The checklist is drawn only from '
    'what the message actually asks for; never invent a requirement, never list anything as '
    'already done, and never include the signature, the confidentiality footer or quoted '
    'earlier mail. If the message asks for nothing concrete, return an empty checklist.')


def extract_ask(msg: dict, llm=None) -> dict:
    """{'summary', 'checklist'} for a task made by hand.

    task_from_message used to store the raw body sliced at 1000 characters, so the task's ask
    was the whole email - greeting, signature, legal footer and the quoted thread underneath -
    and there was no checklist at all, because nothing had asked for one (the owner, 2026-09-10:
    "shouldn't the ai triage pull out just the task?"). It should, and now the hand road asks
    the same question the automatic one does.

    No brain, or a brain that fails: fall back to `own` - what the sender typed THIS time, which is
    the ask itself and never the chain under it. The model still sees the chain, quoted (sender_body).
    """
    raw_body = str(msg.get('BodyText') or msg.get('body') or '')
    own_text = msg.get('OwnText') or msg.get('own_text')
    body, _cut = sender_body(raw_body, own_text, budget=6000)
    own = (own_text and strip_boilerplate(str(own_text).strip())) or own_words(raw_body)
    subject = str(msg.get('Subject') or msg.get('subject') or '')
    if not llm: return {'summary': own[:1000], 'checklist': [], 'outputs': []}
    try:
        raw = llm(ASK_SYSTEM, f'Subject: {subject}\n\n{body[:6000]}')
        j = json.loads(re.sub(r'^```(json)?|```$', '', str(raw or '').strip(), flags=re.M))
        summary = str(j.get('summary') or '').strip()
        items = [x.strip() for x in (j.get('checklist') or []) if isinstance(x, str) and x.strip()]
        return {'summary': summary or own[:1000], 'checklist': items[:12], 'outputs': parse_outputs({'intent': 'task', **j})}
    except Exception as e:                       # a promote must never fail because a model did
        from loguru import logger
        logger.warning(f'could not extract the ask, keeping the plain body: {e}')
        return {'summary': own[:1000], 'checklist': [], 'outputs': []}


def parse_outputs(j: dict) -> list:
    """The verdict's outputs - only on a task, only with somebody to send to (slots.clean validates the rest)."""
    if j.get('intent', 'task') != 'task' or not isinstance(j.get('outputs'), list): return []
    return [{'to': str(o.get('to')).strip(), 'about': str(o.get('about') or '').strip()} for o in j['outputs']
            if isinstance(o, dict) and str(o.get('to') or '').strip()][:12]


def repo_choice_of(j: dict, repos: list) -> dict:
    """The verdict's repository, validated against the known ones (PW-094): a name not on the list is
    dropped and becomes the owner's choice, as does anything the model called ambiguous."""
    known = {str(r.get('repo') or '').strip().lower(): str(r.get('repo') or '').strip() for r in repos if r.get('repo')}
    named = str(j.get('repository') or '').strip()
    reason = ' '.join(str(j.get('repo_reason') or '').split())[:200]
    if named and named.lower() not in known:
        return {'repository': None, 'needs_repo_choice': True,
                'repo_reason': f'triage named a repository that is not configured ({named[:60]})' + (f' - {reason}' if reason else '')}
    repo = known.get(named.lower()) if named else None
    needs = bool(j.get('needs_repo_choice')) or (repo is None and len(known) > 1 and j.get('kind') == 'coding')
    return {'repository': repo if not bool(j.get('needs_repo_choice')) else None, 'needs_repo_choice': needs, 'repo_reason': reason}


REPO_ABOUT = 600        # how much of a repository's description the routing question is given

RELATIONSHIPS = ('new', 'continues', 'answers', 'uncertain')


def relationship_of(j: dict, candidates: list) -> dict:
    """The verdict's relationship, validated against the same-day room lines it was shown (PW-033):
    ids outside them are dropped, a task id must be one of theirs, and a join with nothing valid
    left to join - or an unknown word - is `uncertain`, which joins nothing."""
    ids = {int(c['id']) for c in candidates if c.get('id') is not None}
    tasks = {int(c['task_id']) for c in candidates if c.get('task_id')}
    rel = str(j.get('relationship') or 'uncertain').strip().lower()
    if rel not in RELATIONSHIPS: rel = 'uncertain'
    related = []
    for x in (j.get('related_message_ids') or []):
        try: v = int(x)
        except (TypeError, ValueError): continue
        if v in ids and v not in related: related.append(v)
    try: task = int(j.get('existing_task_id')) if j.get('existing_task_id') is not None else None
    except (TypeError, ValueError): task = None
    if task not in tasks: task = None
    if rel in ('continues', 'answers') and not related and task is None: rel = 'uncertain'
    # ...and held to its OWN answer: asked outright whether this line is the same problem as the one it continues,
    # a model that says no has named a second job. Definitions alone did not move it - a sender's "it says AI not set up"
    # and "it is not re-triaging" joined the DLL-update task six times in six (the owner, 2026-09-24: "different
    # issues are separate tasks")
    if rel == 'continues' and j.get('same_problem') is False: rel = 'new'
    return {'relationship': rel, 'related_message_ids': related, 'existing_task_id': task}


def classify_intent(msg: dict, llm=None, soul: str = None, notes: list = None, images=None,
                    learned: str = None, system: str = None, notes_left: int = 0, mine=(),
                    thread: dict = None, watch: str = None, playbooks: str = None,
                    project: dict = None, candidates: list = None, repos: list = None,
                    profiles: str = None, routing_history: list = None, seen: set = None) -> dict:
    """`notes` are the owner's past verdicts that may bear on this message - each one dated,
    with the sender and subject it was given on - selected by sender and topic overlap
    (ingest.relevant_notes). They are EVIDENCE: the model judges how alike this message is,
    which a keyed rule could not (the same topic can arrive asking something new).

    `images` are the attached screenshots, for a model that can see them. Half of "see below"
    mail says nothing in its body - triage read three words and filed it as informational.

    `thread` is what the messages AROUND this one say - chiefly whether a colleague has already
    replied. Supplied as a signal for the same reason as the To/Cc lines: the code's job is to
    put the fact in front of the model, and how much it counts for is a judgement that belongs
    in TRIAGE.md where the owner can argue with it.

    `watch` is a SCHEDULED REPORT's standing brief: why the owner set the report up and what
    would count as something being off in it. A report is a message like any other here, and
    without the brief the classifier is reading a table of numbers with no idea which numbers
    would be bad - so every run came out fyi, which made the whole "a report can start work"
    road dead on arrival. With it, the report's own definition of wrong is what decides.

    `system` is TRIAGE.md, the owner-editable classifier instructions - HTML comments are
    stripped (the doc's own how-to-edit note is for the owner, not the model), and a blanked
    doc falls back to the shipped default. An edit that breaks the JSON contract degrades to
    the keyword heuristics, never to a crash.

    `candidates` (chat only) are the lines of the SAME room on the SAME local calendar day as the
    message - [{id, who, when, text, task_id}] - and asking for them makes the verdict also answer
    `relationship` (new | continues | answers | uncertain) with `related_message_ids` and an
    optional `existing_task_id`, all validated against exactly these lines (PW-031/032/033). A
    prior day is new whatever it resembles; `uncertain` joins nothing; an id outside the room or
    the day is dropped. This replaced a second classifier (same_ask) that could disagree with
    this one about the same line.

    `repos` are the known repositories - [{repo, about}] from the SOUL map and the learned project
    graph. Given, the verdict also names `repository` (one of them or null), `needs_repo_choice` and
    `repo_reason` for a task; the sender's project associations (project_context) are supporting
    evidence, never proof. Validated by repo_choice_of (PW-092/094): an unknown name is dropped and
    turns into a choice for the owner, as does anything the model calls ambiguous.

    `playbooks` is the menu of the owner's playbooks (playbooks.menu: slug, title and `when` each).
    A message that is an instance of one is answered with its slug, and that slug is what seeds
    the session with the playbook instead of a coder's repository rules. Matching is a judgement
    about the message, so it is made here, by the model that read it - never by a keyword rule."""
    raw_answer, parse_error = None, None
    if llm:
        try:
            base = re.sub(r'<!--.*?-->', '', system or '', flags=re.S).strip() or INTENT_SYSTEM
            # every signal in this payload the document says nothing about, explained in the shipped
            # words: a field handed over unexplained is a field the model guesses at, and the exchange
            # (the prior mail on the thread) reached this install's generated doc as an unnamed key
            unsaid = [t for k, t in FIELDS.items() if (thread or {}).get(k) and k not in base]
            if unsaid: base += '\n\nTHE PAYLOAD ALSO CARRIES:\n' + '\n'.join(unsaid)
            # ...and the same for what the ANSWER must carry. A generated document describes how to
            # judge and never restates the output shape, so asking for it again here is not
            # overriding the owner - it is the half of the prompt the document was never writing.
            # It is added LAST (below), not here: appended to the document it sat 16,000 characters
            # from the answer, under the soul, the evidence, the playbooks and the repositories,
            # while the document's own opening line named a contract with no title and no summary.
            # On a long forwarded mail the model answered that line and dropped both, and the card
            # fell back to the raw body (TQ-0665, three times in eight replays). A SHAPE cannot
            # argue with the owner's judgement, so nothing is lost by asking for it at the end.
            shape = 'checklist' not in base or '"summary"' not in base
            system = base + (f"\n\nOperator's document:\n{soul[:2500]}" if soul else '')
            # `learned` is LEARNED.md's active sections: the profile distilled from the owner's
            # past verdicts. It refines the operator's document; explicit notes still outrank it.
            if learned:
                system += ("\n\nLearned profile - patterns distilled from the owner's past verdicts "
                           '(the document above outranks it where they disagree):\n' + learned[:1500])
            if notes:
                # already ranked and budgeted by ingest.relevant_notes. Evidence, never an order (PW-025): how much
                # each counts for is the guide's to say (templates/triage.md, section 6).
                system += ('\n\nEVIDENCE - verdicts the owner gave on earlier mail that looks related (each names the sender '
                           'and subject it was given on):\n' + '\n'.join(f'- {n}' for n in notes)
                           + (f'\n({notes_left} further note(s) also apply to this sender but did not fit.)' if notes_left else ''))
            # From here down the code only LABELS what it hands over. Every sentence about how to judge it - the
            # report brief, the workers, kind, repositories, chat lines, same_as - lives in the guide (2026-10-09:
            # the owner, "why are there items in code in triage? I thought we removed them").
            if watch: system += "\n\nTHE REPORT'S BRIEF - why the owner runs this report and what they watch for:\n" + str(watch)[:1200]
            if playbooks: system += "\n\nPLAYBOOKS - the owner's written procedures, each with the arrival that starts it (when):\n" + str(playbooks)[:3000]
            if profiles: system += '\n\nTHE WORKERS - the specialists for non-coding work, each with what it is for:\n' + str(profiles)[:2000]
            same_ids = {int(w['tid']) for key in ('open_work', 'recently_closed') for w in ((thread or {}).get(key) or []) if w.get('tid')}
            how = addressed_to_you(msg, mine)
            # THE SENDER'S OWN WORDS ON TOP, the chain they wrote on top of quoted under them, and the
            # budget's cut taken out of the chain (sender_body). `own_text` is Graph's uniqueBody where
            # the mailbox carried one: the mailbox saying where the ask ends beats guessing at it.
            body_text, body_cut = sender_body(str(msg.get('body') or ''), msg.get('own_text'), known=seen)
            # ...and WHO, by name: only the address went in, so the model made a name out of it - "hamos@" became "Hamos"
            # in the summary every surface leads with (the owner, 2026-09-28: "it should pull the correct name")
            user = json.dumps({'from': msg.get('from_email'), **({'from_name': person_name(msg.get('from_name'))} if person_name(msg.get('from_name')) else {}),
                               'subject': msg.get('subject'),
                               **({'addressed_to_you': how,
                                   'recipients': len(msg.get('to') or []) + len(msg.get('cc') or [])} if how else {}),
                               **(thread or {}),
                               **({'project_context': project} if project else {}),
                               **({'routing_history': routing_history} if routing_history else {}),
                               **({'same_day_lines': [{k: c.get(k) for k in ('id', 'who', 'when', 'text', 'task_id')} for c in candidates]}
                                  if candidates is not None else {}),
                               # 160 cut every real description mid-clause - taskuary lost "do the work, you approve", ledger
                               # lost the noun its whole sentence was about. This is the one line the model routes on.
                               **({'known_repositories': [{'repo': r.get('repo'), 'about': (r.get('about') or '')[:REPO_ABOUT]} for r in repos]} if repos else {}),
                               **({'body_truncated': True} if body_cut else {}),
                               # what "by Friday" counts from (DUE)
                               **({'sent_on': str(msg['sent_at'])[:10]} if msg.get('sent_at') else {}),
                               'body': body_text,
                               # the shape once more, under the message, because a LONG message is what
                               # loses it: on 8,400 characters of forwarded mail the model answered the
                               # document's own contract line and dropped title and summary in three of
                               # eight replays; asked here too, sixteen of sixteen carried them (TQ-0665).
                               **({'answer': 'the JSON object the instructions describe, including '
                                             '"title" and "summary" - and "checklist" for a task'} if shape else {})})
            if images: system += '\n\nImages from the message are attached.'
            # ...and "urgent" on its own (2026-09-25): a document written before triage decided urgency never asks for
            # it, and the owner's document is otherwise left as they wrote it
            # ...urgent and due are in the shape block, so they ride on their own only when it is not sent
            if not shape and '"urgent"' not in base: system += '\n\n' + URGENT
            if not shape and '"due"' not in base: system += '\n\n' + DUE          # ...and the due day (2026-10-06)
            # the last thing asked for, after every block that says how to JUDGE: the output shape
            if shape: system += '\n\n' + TASK_FIELDS
            # ...and the shape goes on the WIRE as well, where the brain has one: a schema the
            # provider enforces cannot be talked out of by a longer message. `need` is the recheck
            # behind it, for a CLI brain that has no wire to put a schema on - one more ask, naming
            # what was left out. Both exist because neither reaches every brain (TQ-0665).
            from .llm import ask_json
            answer = ask_json(llm, system, user, want=verdict_schema(repos, candidates, playbooks, profiles, same=bool(same_ids)),
                              need=('title', 'summary'), **({'images': images} if images else {}))
            raw_answer, j = answer.raw, answer.data
            if j is None: raise ValueError(answer.error or 'the response was not JSON')
            if j.get('intent') in ('task', 'reply_only', 'fyi'):
                # `kind` is the model's SECOND verdict and it ROUTES the task to one of three
                # places: coding starts an agent, general opens the assistant's chat, task goes on
                # the owner's own list with nothing working it (ingest.auto_start_ok decides who may
                # start the first two unattended). It used to be a regex over the body
                # (routing.draft_task_fields), which is how a Teams line about someone's job scope
                # opened a coding session; the model has read the whole message and TRIAGE.md's
                # definition, so its word wins when given, and the regex is only the fallback.
                out = {'intent': j['intent'], 'why': str(j.get('why') or '')[:240]}
                if j['intent'] == 'task' and j.get('kind') in ('coding', 'general', 'task'): out['kind'] = j['kind']
                # a playbook the menu actually offered rides on the task as ITS PROCEDURE; it says how the job
                # is done here, not who does it - the kind stays the model's own (PW-205: the old override to
                # coding sent a PTO request, a general job, into a checkout)
                pb = str(j.get('playbook') or '').strip().lower()
                if playbooks and pb and out['intent'] == 'task' and re.search(rf'^- {re.escape(pb)}: ', playbooks, re.M):
                    out['playbook'] = pb
                # WHICH WORKER, when one starts: validated against the roster it was actually shown, the
                # same way the playbook is. A name nobody offered is dropped, and the task falls to the
                # default profile - a hallucinated worker must not route work anywhere.
                pr = str(j.get('profile') or '').strip().lower()
                if profiles and pr and out['intent'] == 'task' and re.search(rf'^- {re.escape(pr)}: ', profiles, re.M):
                    out['profile'] = pr
                if candidates is not None: out.update(relationship_of(j, candidates))
                # same_as: only a tid it was actually shown - a task it made up joins nothing
                try: same = int(j.get('same_as')) if j.get('same_as') is not None else None
                except (TypeError, ValueError): same = None
                if same in same_ids: out['same_as'] = same
                if repos and out['intent'] == 'task': out.update(repo_choice_of(j, repos))
                # the work, named (PW-074): a title and summary of what was asked - validated, never
                # trusted; the router falls back when absent. Kept on EVERY verdict now, not only on
                # the two that become work: an fyi and a triaged report are rows the owner reads too,
                # and they have no task to hold a title, so the rail fell back to the mail header
                # (the owner, 2026-09-16; ingest writes it to message.TriageTitle, funnel.says reads
                # it). Gating the pair on the verdict is the same bug twice - it is how a question
                # triage answered came to wear a lowercased subject over the whole mail (2026-09-14).
                # The CHECKLIST stays the task's: what a reply owes is the reply, and an fyi owes nothing.
                title = ' '.join(str(j.get('title') or '').split())[:120]
                summary = str(j.get('summary') or '').strip()[:1000]
                if title: out['title'] = title
                if summary: out['summary'] = summary
                # urgent only means something on work: an fyi that says "urgent" is still an fyi
                if j.get('urgent') is True and out['intent'] in ('task', 'reply_only'): out['urgent'] = True
                if out['intent'] in ('task', 'reply_only') and due_of(j, msg.get('sent_at')): out['due'] = due_of(j, msg.get('sent_at'))
                if out['intent'] == 'task' and isinstance(j.get('checklist'), list):
                    out['checklist'] = [x for x in j['checklist'] if isinstance(x, str)]
                if out['intent'] == 'task' and parse_outputs(j): out['outputs'] = parse_outputs(j)
                return out
            parse_error = f"invalid intent {j.get('intent')!r}; expected task, reply_only, or fyi"
        except Exception as e:
            parse_error = f'{type(e).__name__}: {e}'
    # An LLM was supplied, answered, and the answer was not usable (bad JSON, an intent outside
    # the contract). That is NOT "no AI configured": heuristic_intent's last branch assumes real
    # work and reads none of the owner's standing notes, so a garbled answer opened a task the
    # owner had already refused - repeatedly, since every retry garbled the same way. Say the
    # verdict is degraded and let the caller file instead of guessing.
    out = heuristic_intent(msg, mine)
    if not llm:
        return out
    # A CLI can emit a whole transcript if an output flag changes. Preserve enough to diagnose
    # the contract failure without letting one response overwhelm SQLite or the Triage tab.
    raw = raw_answer or ''
    if len(raw) > 8000:
        raw = raw[:8000] + '\n… [triage output truncated at 8,000 characters]'
    return {**out, 'degraded': True, 'raw_output': raw,
            'parse_error': (parse_error or 'the response was not a usable verdict')[:1000]}


# ── one chat, several jobs ───────────────────────────────────────────────────────────────
# A chat room is not a topic. Mail threads itself - a reply carries the References header and
# belongs to what came before it by construction - but teams:<chat> and whatsapp:<jid> are a
# ROOM, and everything anyone ever says in it shares one id. Routing read that id as "the same
# thread" (routing.WEIGHTS: thread=1.0 clears the attach bar alone), so eleven lines from one
# person over an hour - four different problems and a screenshot - became ONE task carrying one
# prompt, and an agent sent at it only ever saw the first ask (owner, 2026-09-02).
#
# Nothing mechanical can split that. A gap in minutes cannot tell "let me rephrase that" from
# "Also, separate thing:", and neither can a keyword - "also" opens both. What CAN tell is a
# reader, so the reader decides, on the one question that matters, with the exchange in front of
# it: the lines they sent AND the answers we sent back, in order, because a reply of ours is the
# clearest boundary there is.
