"""Intent triage: is a message a TASK (something to DO), a quick REPLY_ONLY question, or
FYI noise? Heuristic by default; pass any `llm(system, user) -> str-json` callable to
upgrade (provider-agnostic - wire your own OpenAI/Anthropic/local call in config).
"""
import json, re
import re as _re

# What each verdict COSTS is part of the judgement, so it is in the prompt: a task starts a
# real agent in a real repo; a reply is one cheap draft the owner approves. Defaulting to
# "task" turned questions into background work nobody asked for.
# `kind` costs something too, and this is the ONE place that decides it: coding starts a
# session, general opens a non-coding conversation, and task leaves the job on the owner's list.
# Nothing downstream re-reads the mail
# to second-guess it - no keyword, sender or category rule anywhere else (owner, 2026-08-30,
# after a training reminder got a coder run: the exception is "clearly not a coding job",
# and it is judged here, in a document that can be argued with).
# This text also ships as templates/triage.md - the editable TRIAGE.md doc that overrides it
# (see classify_intent's `system` param). It stays here too as the fallback for a blanked doc.

# The evidence fields the payload carries, each with what it MEANS. An owner-written (or
# history-generated) TRIAGE.md replaces these instructions wholesale, so a signal added to the
# payload after that document was written arrives with nothing said about it - this install's doc
# names neither `exchange` nor `assistant_said` (2026-09-03). What a field means is a data
# dictionary, not a judgement, so classify_intent appends the ones the document never names.
FIELDS = {
    'others_replied':
        'others_replied names people - other than you and the sender - who have already SENT a message on '
        'this thread, and last_on_thread is whoever spoke most recently. Somebody else answering is the '
        'strongest everyday sign that a request is not waiting on you: when a colleague has replied and the '
        'ask is not aimed at you specifically, prefer fyi. Weigh it, do not obey it - a question that names '
        'you, or that only you can answer, is still yours however many colleagues are on the thread. Absent '
        'fields mean nobody else has spoken, which is not evidence either way.',
    'exchange':
        'exchange is the recent back-and-forth on this thread or in this chat room, oldest first - each message\'s own words once, quoted copies and signatures removed - with the '
        'owner\'s own lines marked "you" - a chat line quotes nothing and a mail reply may quote nothing '
        'either, so it is the only reliable way to know what a bare "nope, new one" or "she wants them back '
        'on" is answering. It is CONTEXT: judge the message in body and nothing else. A line that answers '
        'something the owner asked in the exchange is a round trip, not a new job. A line opening a subject '
        'the exchange has not touched is a new ask on its own merits, however the earlier lines were '
        'classified. Being about the same system or person is not the same ask: two bugs in one app are two '
        'jobs. But an ask made two messages back is STILL THE ASK: when somebody asked for something and the '
        'exchange shows it was never delivered, that thread is live work, and a message moving it on - a '
        'decision, an approval, a name with authority behind it ("Hindy wants them back on"), a changed '
        'requirement, a nudge - is a task, however conversational it reads and however little it asks in its '
        'own words. Only a thread whose ask was plainly settled or dropped goes to fyi.',
    'idea_context':
        'idea_context means this line was GENERATED by the Timeline assistant, not sent by a person: it names the '
        'report the idea came from, the task it is about (with its status) and whether a worker has that task. '
        'Judge it like any arrival - fyi when it only informs, task when something must be done and nobody has it, '
        'reply_only when a sentence settles it. A task somebody is already working is not new work; a claim in '
        'the idea that something was done is not evidence that it was.',
    'assistant_said':
        'assistant_said is what the Timeline assistant already raised about this very thread (a follow-up it '
        'suggested, an ask it flagged, a promise it noticed) and what the owner did with it. Be consistent '
        'with it, not obedient: an OPEN follow-up means the owner is waiting on this person and their line is '
        'probably the answer (a round trip, not new work); a DISMISSED one means the owner let the thread go - '
        'do not resurrect it. Say when you disagree.',
}

# WHAT THE ANSWER MUST CONTAIN, as opposed to what the verdict should BE. Named separately
# because an owner-written or generated TRIAGE.md REPLACES INTENT_SYSTEM wholesale, and this
# install's (UpdatedBy=histgen) never mentions title, summary or checklist - so the model
# answered intent/kind/why only, ingest fell back to routing.draft_task_fields' body[:1000],
# and every task carried the whole email as its ask, signature and legal footer included, with
# no todos at all (the owner, 2026-09-10). classify_intent re-appends this when the document
# omits it, for exactly the reason it re-appends FIELDS: the output SHAPE is a contract, not a
# judgement, and the document is only entitled to the judgement.
TASK_FIELDS = (
    'For a task, also answer "title" (what the work is, 12 words max), "summary" (what was asked and by whom, '
    'two sentences - the ask itself, never the signature, the confidentiality footer or quoted earlier mail) and '
    '"checklist": ["<one distinct requested outcome each>"] - drawn only from what the message and exchange '
    'actually ask for; never invent a requirement, never list anything as already done.')

INTENT_SYSTEM = (
    'Classify one inbound work message. Answer JSON only: '
    '{"intent": "task|reply_only|fyi", "kind": "coding|general|task", "profile": "<a name from THE WORKERS, when any are listed>", '
    '"why": "<one concrete sentence: what you saw in the message '
    'and which rule it hit - the owner reads this to judge the verdict, 25 words max>"}.\n'
    'Almost everything that asks for anything is a task, and almost every task goes to the coding agent '
    'automatically: it does what can be done from a keyboard or says "nothing to do here" and stops - a cheap ending.\n'
    'kind ROUTES the task to one of three places, so answer it as its own question:\n'
    '  coding - a capable person could do this from a keyboard, given access to the systems. An agent starts on '
    'it. A system to change, an account to unlock, a database to query, a file or report to produce, a document to '
    'draft, a vendor to chase by writing to them, something to look up: all coding. This is the DEFAULT.\n'
    '  general - nothing to type at a system, but thinking, reading or research would help: weigh an option, make '
    'sense of a thread, work out what to ask, get ready for something. It opens a CONVERSATION with the assistant.\n'
    '    An OUTAGE or an access problem in somebody else\'s system - "the payroll portal is down for everyone", '
    '"nobody can log into the badge reader", "who can look at this??" - is general, not coding: the agent works in '
    'a code checkout and cannot reach that system, so the useful answer is who to tell and what to say, not a '
    'session in the wrong repository. Coding is for systems this install has the code or the credentials for.\n'
    '  task - a person has to do it in the world, and no amount of typing or thinking does it: a course to sit, a '
    'form to physically sign, a meeting to attend, a call somebody has to make, a decision only the owner can take. '
    'It goes on the owner\'s own list and nothing works it. Say task, too, when the owner\'s past verdicts say this '
    'kind of work is not for an agent.\n'
    'Cannot tell? Say general: an assistant reads and thinks about anything; a coding session started on a guess works in the wrong place.\n'
    'Both verdicts are yours and nothing downstream second-guesses either. Never shade one to steer the other.\n'
    'task = someone must DO something beyond writing back: change a system, fix or build something, produce or '
    'chase something, look something up that takes more than a sentence.\n'
    'reply_only = the answer is a sentence the owner already knows - "what time are you free", "are you around '
    'Tuesday", "which file did you mean". Nothing to look up, change or produce; a question with a lookup or a fix '
    'behind it is a task. The reply is drafted for the owner to approve.\n'
    'fyi = informational only: notices and reports that tell the owner something and want nothing back, '
    'newsletters, thanks, threads the owner is merely copied on. Read the ask, not the sender: an automated '
    'notice that puts something on the owner\'s plate - a training assignment with a due date, an expiring '
    'password, a form to sign - is a task, because somebody has to do it; one that only says what already '
    'happened is fyi. Whether an AGENT could do that task is kind\'s question, not this one - never downgrade '
    'a real obligation to fyi because no agent can help with it.\n'
    'Chat is not mail (no subject, no recipient lines) but an ask in chat is still an ask - a task for the agent. '
    'reply_only is for what a sentence settles with nothing to do behind it; fyi is thanks, status, and threads '
    'between other people where the owner is neither asked nor named.\n'
    'addressed_to_you and recipients are SIGNALS to weigh, never rules to obey. "to" = the mail was aimed at the owner; "cc" = they were copied, which OFTEN means somebody else owns the work; "not named" = it arrived through a group alias or a shared mailbox the owner is responsible for - their own address is not on it, and the people on the To line own the matter. But a cc can absolutely be theirs: one that names them, asks them something directly, or that only they can answer is their work, and being on the cc line counts for nothing against that. recipients counts everyone on the mail - a note to thirty people is more likely a broadcast than a job. Weigh these with everything else in the message; never decide on them alone. Both fields are absent on channels with no recipient lines.\n'
    + FIELDS['others_replied'] + '\n'
    + FIELDS['exchange'] + '\n'
    + FIELDS['assistant_said'] + '\n'
    + TASK_FIELDS + '\n'
    'Torn between task and reply_only? Choose task. Torn between task and fyi? Choose task unless the mail plainly asks '
    'nobody for anything - a task the owner glances at and drops costs less than a job nobody did, and a drafted reply '
    'is no substitute for either.')

def addressed_to_you(msg: dict, mine=()) -> str:
    """'to', 'cc', 'not named', or '' when the channel carries no recipient lines at all (chat) -
    the one fact that separates "this is mine" from "I am watching someone else's thread", and it
    was never collected, so no classifier could ever weigh it. The ADDRESSES are deliberately not
    returned: what reaches a prompt is the relationship, never the mailbox (0.2.1, no addresses in
    prompts)."""
    # EVERY address that is the owner, not just the mailbox this copy landed in. Mail to a
    # shared or journal mailbox is still addressed to them when their own address is on the Cc
    # line - and comparing only the arrival mailbox called that 'not named', which is exactly
    # backwards for the case the whole signal exists to catch.
    # `mine` is the owner's OWN address(es) (ingest.own_addresses). When the caller knows them,
    # the mailbox this copy arrived in is NOT added: a shared or journal mailbox Taskuary polls
    # receives everybody's mail, and counting it as "me" made every message to it read as
    # aimed at the owner (2026-08-27: a refund question to devteam-logs@ came out as 'to').
    # With no `mine` at all, the arrival mailbox is the only "me" there is.
    me = {str(a).lower() for a in mine if a} or {a for a in {(msg.get('source_name') or '').strip().lower()} if a}
    to = {str(a).lower() for a in (msg.get('to') or [])}
    cc = {str(a).lower() for a in (msg.get('cc') or [])}
    if not me or not (to or cc): return ''
    return 'to' if me & to else 'cc' if me & cc else 'not named'


_ASK = re.compile(r'\b(can you|could you|are you|do you|would you|let me know|please confirm|any update)\b', re.I)
_ACT = re.compile(r'\b(please (add|send|update|fix|remove|create|set up)|need you to|action required|please complete)\b', re.I)
_FYI = re.compile(r'\b(fyi|for your (records|reference)|no action (needed|required)|auto-?generated|this is an automated|do not reply)\b', re.I)


def heuristic_intent(msg: dict, mine=()) -> dict:
    body = (msg.get('body') or '').strip()
    low = f"{msg.get('subject') or ''} {body[:600]}"
    if _FYI.search(low) and not body.rstrip().endswith('?'):
        return {'intent': 'fyi', 'why': 'carries automated/no-action markers and asks no question (keyword heuristic)'}
    if _ACT.search(low): return {'intent': 'task', 'why': 'explicitly asks for something to be done (keyword heuristic)'}
    if body.rstrip().endswith('?') or _ASK.search(low):
        return {'intent': 'reply_only', 'why': 'reads as a question an answer settles (keyword heuristic)'}
    # A cc used to be FILED here, by keyword, before any model saw it - which is the one thing
    # the To/Cc signal must not do. Plenty of cc'd mail is genuinely yours: the sender put the
    # owner in cc and addressed them in the body, or they are the only person who can answer.
    # Deciding that from the header alone is a guess wearing a rule's clothing, so the fields
    # are handed to the classifier as evidence and the classifier decides. It costs one AI call
    # on quiet cc mail that this used to settle for free; being right is worth more.
    return {'intent': 'task', 'why': 'no fyi markers and no plain question - assumed real work (keyword heuristic, no AI read this)'}


# ── the message, minus the wrapper ──────────────────────────────────────────────────────
# Corporate mail arrives half signature: name, title, phone block, an inspirational quote,
# and a confidentiality NOTICE longer than the ask. All of it rode into every AI call - the
# triage, the seeded session, the reply drafts - spending context on boilerplate. The STORED
# body stays whole (the panel shows the real mail); only what is fed to an AI is trimmed,
# and always conservatively: when in doubt, keep.
# the heading alternative is case-SENSITIVE (or title case with a colon): a footer shouts NOTICE;
# "Notice the error at the top - can you fix it" is the ask, and a case-blind match threw it and
# everything after it away before triage ever saw it (audit 2026-09-02)
_LEGAL = _re.compile(r'^\s*(NOTICE|DISCLAIMER|CONFIDENTIALITY( NOTICE)?|LEGAL NOTICE)[:\s]'
                     r'|^\s*(Notice|Disclaimer|Confidentiality Notice|Legal Notice):'
                     r'|(?i:this (e-?mail|message|communication)[^.]{0,120}(confidential|privileged|intended (solely|only))'
                     r'|if you (are not the intended|have received this[^.]{0,40}in error)'
                     r'|unauthorized (use|review|disclosure|distribution))')
_VALEDICTION = _re.compile(r'^\s*(thank(s| you)|best( regards| wishes)?|kind(est)? regards|regards|'
                           r'sincerely|respectfully|warm(ly| regards)?|cheers|v/?r)\s*[,!.]*\s*$', _re.I)
# ...and the shapes a mail client actually writes them in: Outlook's phone dash is U+2011, and it
# pads a signature block with zero-width spaces (which str.strip() does not remove, so the block
# read as ordinary text). The \b ending the first alternative had been eaten to a literal backspace,
# so a bare 'Phone:' or 'Email:' line never matched and every signature rode into the prompt.
_DASH = '\u2010\u2011\u2012\u2013\u2014\u2212-'
_BLANKISH = _re.compile(r'^[\s\u200b\u200c\u200d\ufeff\u00a0]*$')
_CONTACT = _re.compile(r'^\s*(phone|tel|mobile|cell|fax|office|direct|email|e-?mail|web|www\.|address)\b'
                       r'|^\s*\+?[\d(][\d\s().x' + _DASH + r']{6,}$'
                       r'|^[^@\s]+@[^@\s]+\.[a-z]{2,}\s*$', _re.I)
_KEEP_MIN = 30          # never trim a message down past this - when in doubt, keep
# the corporate wrapper AROUND a body, not the sender's words: the external-mail banner and the
# "you don't often get email" hint (one pattern for every surface - assistant.py imports it)
_BANNER = _re.compile(r"(this email was sent from outside of[^*\n]*(\*\*[^*]*\*\*)?\s*|"
                      r"\[?\s*you don'?t often get email from \S+\.?( learn why this is important( at \S+)?)?\s*\]?)", _re.I)
# footer clutter: a mail client's stamp, a newsletter's unsubscribe strip - whole lines made of these
_CLUTTER_BIT = (r"(sent from my [\w ]+|get outlook for (ios|android)|sent via [\w ]+|unsubscribe( here| from this list)?|"
                r"manage (your )?(email )?preferences|view (this )?(email )?in (your )?browser|update your preferences|opt out)")
_CLUTTER = _re.compile(r'^\s*(' + _CLUTTER_BIT + r')(\s*[|·•\-]\s*' + _CLUTTER_BIT + r')*\s*\.?\s*$', _re.I)
BODY_BUDGET = 6000      # the current body reaches the model whole up to this; a cut is disclosed, never silent
EXCHANGE_BUDGET = 12000
NL = chr(10)


def strip_boilerplate(text: str) -> str:
    """The words the sender actually typed: the legal footer and the signature block go,
    everything before them stays byte-for-byte."""
    lines = [l for l in _BANNER.sub('', text or '').splitlines() if not _CLUTTER.match(l)]
    # 1. the legal footer: from the first legalese line to the end
    for i, l in enumerate(lines):
        if _LEGAL.search(l) and len(NL.join(lines[:i]).strip()) >= _KEEP_MIN:
            lines = lines[:i]
            break
    # 2. the signature: a closing valediction in the tail, followed by the name/title/phone block
    tail_from = max(1, len(lines) - 14)
    for i in range(len(lines) - 1, tail_from - 1, -1):
        if _VALEDICTION.match(lines[i]) and len(NL.join(lines[:i]).strip()) >= _KEEP_MIN:
            lines = lines[:i]
            break
    # 3. stray contact lines left at the very end (a block with no valediction above it)
    while lines and (_CONTACT.match(lines[-1]) or _BLANKISH.match(lines[-1])):
        if len(NL.join(lines[:-1]).strip()) < _KEEP_MIN: break
        lines.pop()
    out = NL.join(lines).rstrip()
    return out if out.strip() else (text or '')


# a quoted copy of an earlier mail inside a reply - only when its words are ALREADY in the chain
_QUOTE_HEAD = _re.compile(r'^\s*(on .{6,160} wrote:\s*$|-{2,}\s*original message\s*-{2,}|-{2,}\s*forwarded message\s*-{2,}|_{5,}\s*$)', _re.I)
_MAIL_HDR = _re.compile(r'^\s*(from|sent|to|cc|subject|date):\s', _re.I)


def _norm_line(l: str) -> str:
    """Remove quote framing without erasing case, operators or literal spacing."""
    text = _re.sub(r'^\s*(?:>\s+)+', '', str(l or ''))
    return text.strip()


def dedupe_quoted(body: str, priors) -> str:
    """Each message's own words once (PW-028). A quoted block - '> ' lines, or everything under an
    'On ... wrote:' / 'Original Message' / 'Forwarded message' head - is dropped only when its lines
    are already in `priors` (the cleaned bodies of the chain so far); unique forwarded material and
    a quote of something the chain does not hold stay, and inline answers keep their own lines with
    the quoted questions they answer removed. The stored message is never edited."""
    known = {_norm_line(l) for p in priors for l in str(p or '').splitlines() if _norm_line(l)}
    lines, out, i = str(body or '').splitlines(), [], 0
    while i < len(lines):
        l = lines[i]
        if l.lstrip().startswith('>'):
            # A run of quote-prefixed lines is one block. Dropping its familiar lines one by
            # one can splice a new instruction out of its context, so keep the whole run when
            # any substantive line is new. A single quoted question in an inline reply remains
            # removable because the sender's unquoted answer ends that run.
            quoted = []
            while i < len(lines) and lines[i].lstrip().startswith('>'):
                quoted.append(lines[i].lstrip()[1:].strip())
                i += 1
            subst = [_norm_line(x) for x in quoted if _norm_line(x)]
            if not subst or any(x not in known for x in subst): out.extend(quoted)
            continue
        head = _QUOTE_HEAD.match(l) or (_re.match(r'^\s*from:\s', l, _re.I) and i + 1 < len(lines) and _re.match(r'^\s*(sent|date):\s', lines[i + 1], _re.I))
        if head:
            rest = [x for x in lines[i + 1:] if not _MAIL_HDR.match(x)]
            subst = [_norm_line(x.lstrip('> ').strip()) for x in rest if _norm_line(x)]
            if subst and all(x in known for x in subst): break                           # an exact copy of what the chain holds
            # Mixed quoted/forwarded blocks stay whole: a familiar majority is not evidence
            # that the remaining lines are disposable. Header fields alone are still wrapper.
            out.extend(x.lstrip('> ') if x.lstrip().startswith('>') else x for x in rest); break
        out.append(l); i += 1
    return '\n'.join(out).rstrip()


# The same two sentences the full verdict is asked for, and the same checklist rule, so a task
# born by hand reads like one born from triage. Deliberately NOT a second opinion on kind,
# repository or playbook: promoting is the owner saying "this is work", and re-litigating that
# is how a hand-made task would end up somewhere they did not put it.
ASK_SYSTEM = (
    'You are reading one message that the owner has just turned into a task. Answer ONLY with a '
    'JSON object: {"summary": "<what was asked and by whom, two sentences>", '
    '"checklist": ["<one distinct requested outcome each>"]}. The checklist is drawn only from '
    'what the message actually asks for; never invent a requirement, never list anything as '
    'already done, and never include the signature, the confidentiality footer or quoted '
    'earlier mail. If the message asks for nothing concrete, return an empty checklist.')


def extract_ask(msg: dict, llm=None) -> dict:
    """{'summary', 'checklist'} for a task made by hand.

    task_from_message used to store the raw body sliced at 1000 characters, so the task's ask
    was the whole email - greeting, signature, legal footer and the quoted thread underneath -
    and there was no checklist at all, because nothing had asked for one (the owner, 2026-09-10:
    "shouldn't the ai triage pull out just the task?"). It should, and now the hand road asks
    the same question the automatic one does.

    No brain, or a brain that fails: fall back to strip_boilerplate, which is still the sender's
    own words minus the footer - never worse than what was stored before.
    """
    body = strip_boilerplate(dedupe_quoted(str(msg.get('BodyText') or msg.get('body') or ''), []))
    subject = str(msg.get('Subject') or msg.get('subject') or '')
    if not llm: return {'summary': body[:1000], 'checklist': []}
    try:
        raw = llm(ASK_SYSTEM, f'Subject: {subject}\n\n{body[:6000]}')
        j = json.loads(re.sub(r'^```(json)?|```$', '', str(raw or '').strip(), flags=re.M))
        summary = str(j.get('summary') or '').strip()
        items = [x.strip() for x in (j.get('checklist') or []) if isinstance(x, str) and x.strip()]
        return {'summary': summary or body[:1000], 'checklist': items[:12]}
    except Exception as e:                       # a promote must never fail because a model did
        from loguru import logger
        logger.warning(f'could not extract the ask, keeping the plain body: {e}')
        return {'summary': body[:1000], 'checklist': []}


def repo_choice_of(j: dict, repos: list) -> dict:
    """The verdict's repository, validated against the known ones (PW-094): a name not on the list is
    dropped and becomes the owner's choice, as does anything the model called ambiguous."""
    known = {str(r.get('repo') or '').strip().lower(): str(r.get('repo') or '').strip() for r in repos if r.get('repo')}
    named = str(j.get('repository') or '').strip()
    reason = ' '.join(str(j.get('repo_reason') or '').split())[:200]
    if named and named.lower() not in known:
        return {'repository': None, 'needs_repo_choice': True,
                'repo_reason': f'triage named a repository that is not configured ({named[:60]})' + (f' - {reason}' if reason else '')}
    repo = known.get(named.lower()) if named else None
    needs = bool(j.get('needs_repo_choice')) or (repo is None and len(known) > 1 and j.get('kind') == 'coding')
    return {'repository': repo if not bool(j.get('needs_repo_choice')) else None, 'needs_repo_choice': needs, 'repo_reason': reason}


REPO_ABOUT = 600        # how much of a repository's description the routing question is given

RELATIONSHIPS = ('new', 'continues', 'answers', 'uncertain')


def relationship_of(j: dict, candidates: list) -> dict:
    """The verdict's relationship, validated against the same-day room lines it was shown (PW-033):
    ids outside them are dropped, a task id must be one of theirs, and a join with nothing valid
    left to join - or an unknown word - is `uncertain`, which joins nothing."""
    ids = {int(c['id']) for c in candidates if c.get('id') is not None}
    tasks = {int(c['task_id']) for c in candidates if c.get('task_id')}
    rel = str(j.get('relationship') or 'uncertain').strip().lower()
    if rel not in RELATIONSHIPS: rel = 'uncertain'
    related = []
    for x in (j.get('related_message_ids') or []):
        try: v = int(x)
        except (TypeError, ValueError): continue
        if v in ids and v not in related: related.append(v)
    try: task = int(j.get('existing_task_id')) if j.get('existing_task_id') is not None else None
    except (TypeError, ValueError): task = None
    if task not in tasks: task = None
    if rel in ('continues', 'answers') and not related and task is None: rel = 'uncertain'
    return {'relationship': rel, 'related_message_ids': related, 'existing_task_id': task}


def classify_intent(msg: dict, llm=None, soul: str = None, notes: list = None, images=None,
                    learned: str = None, system: str = None, notes_left: int = 0, mine=(),
                    thread: dict = None, watch: str = None, playbooks: str = None,
                    project: dict = None, candidates: list = None, repos: list = None,
                    profiles: str = None, routing_history: list = None) -> dict:
    """`notes` are the owner's past verdicts that may bear on this message - each one dated,
    with the sender and subject it was given on - selected by sender and topic overlap
    (ingest.relevant_notes). They are EVIDENCE: the model judges how alike this message is,
    which a keyed rule could not (the same topic can arrive asking something new).

    `images` are the attached screenshots, for a model that can see them. Half of "see below"
    mail says nothing in its body - triage read three words and filed it as informational.

    `thread` is what the messages AROUND this one say - chiefly whether a colleague has already
    replied. Supplied as a signal for the same reason as the To/Cc lines: the code's job is to
    put the fact in front of the model, and how much it counts for is a judgement that belongs
    in TRIAGE.md where the owner can argue with it.

    `watch` is a SCHEDULED REPORT's standing brief: why the owner set the report up and what
    would count as something being off in it. A report is a message like any other here, and
    without the brief the classifier is reading a table of numbers with no idea which numbers
    would be bad - so every run came out fyi, which made the whole "a report can start work"
    road dead on arrival. With it, the report's own definition of wrong is what decides.

    `system` is TRIAGE.md, the owner-editable classifier instructions - HTML comments are
    stripped (the doc's own how-to-edit note is for the owner, not the model), and a blanked
    doc falls back to the shipped default. An edit that breaks the JSON contract degrades to
    the keyword heuristics, never to a crash.

    `candidates` (chat only) are the lines of the SAME room on the SAME local calendar day as the
    message - [{id, who, when, text, task_id}] - and asking for them makes the verdict also answer
    `relationship` (new | continues | answers | uncertain) with `related_message_ids` and an
    optional `existing_task_id`, all validated against exactly these lines (PW-031/032/033). A
    prior day is new whatever it resembles; `uncertain` joins nothing; an id outside the room or
    the day is dropped. This replaced a second classifier (same_ask) that could disagree with
    this one about the same line.

    `repos` are the known repositories - [{repo, about}] from the SOUL map and the learned project
    graph. Given, the verdict also names `repository` (one of them or null), `needs_repo_choice` and
    `repo_reason` for a task; the sender's project associations (project_context) are supporting
    evidence, never proof. Validated by repo_choice_of (PW-092/094): an unknown name is dropped and
    turns into a choice for the owner, as does anything the model calls ambiguous.

    `playbooks` is the menu of the owner's playbooks (playbooks.menu: slug, title and `when` each).
    A message that is an instance of one is answered with its slug, and that slug is what seeds
    the session with the playbook instead of a coder's repository rules. Matching is a judgement
    about the message, so it is made here, by the model that read it - never by a keyword rule."""
    raw_answer, parse_error = None, None
    if llm:
        try:
            base = re.sub(r'<!--.*?-->', '', system or '', flags=re.S).strip() or INTENT_SYSTEM
            # every signal in this payload the document says nothing about, explained in the shipped
            # words: a field handed over unexplained is a field the model guesses at, and the exchange
            # (the prior mail on the thread) reached this install's generated doc as an unnamed key
            unsaid = [t for k, t in FIELDS.items() if (thread or {}).get(k) and k not in base]
            if unsaid: base += '\n\nTHE PAYLOAD ALSO CARRIES:\n' + '\n'.join(unsaid)
            # ...and the same for what the ANSWER must carry. A generated document describes how to
            # judge and never restates the output shape, so asking for it again here is not
            # overriding the owner - it is the half of the prompt the document was never writing.
            if 'checklist' not in base or '"summary"' not in base:
                base += '\n\nWHATEVER ELSE YOU ANSWER, THE SHAPE IS FIXED:\n' + TASK_FIELDS
            system = base + (f"\n\nOperator's document:\n{soul[:2500]}" if soul else '')
            # `learned` is LEARNED.md's active sections: the profile distilled from the owner's
            # past verdicts. It refines the operator's document; explicit notes still outrank it.
            if learned:
                system += ("\n\nLearned profile - patterns distilled from the owner's past verdicts "
                           '(the document above outranks it where they disagree):\n' + learned[:1500])
            if notes:
                # already ranked and budgeted by ingest.relevant_notes - re-cutting here is what
                # used to throw away whichever verdicts happened to sit past the 2000th character.
                # When EVERY retrieved verdict says the same thing, that is not a hint to weigh - a
                # refund thread with two NOT OURS on file still opened a reply task while the model
                # "judged likeness". No topic is named here: it counts the verdicts it was handed.
                # ...and never as an ORDER. Two agreeing verdicts used to become "SETTLED BY YOUR
                # OWNER ... no exceptions", which decided the new message unread - a refund thread
                # that this time asked the owner something was filed like all the others. The owner's
                # requirement (PW-025): past evaluations are history the model weighs, and only an
                # explicit standing policy (policy.py) decides without reading.
                system += ('\n\nEVIDENCE - verdicts the owner gave on earlier mail that looks related '
                           '(pulled by sender and by topic; each names the sender and subject it was given on). '
                           'Judge how alike THIS message really is: the same sender asking the same kind of '
                           'thing makes a verdict binding, a shared word does not, and a thread that is now '
                           'asking the owner something new is new. Where a verdict plainly fits, follow it:\n'
                           + '\n'.join(f'- {n}' for n in notes)
                           + (f'\n({notes_left} further note(s) also apply to this sender but did not fit. '
                              'Say so in your reason if the verdict feels underdetermined - do not claim '
                              'nothing is on file.)' if notes_left else ''))
            # No rule about the To/Cc lines is appended here any more. The code's job is to
            # SUPPLY the signal; how much it counts for is a judgement, and judgement belongs in
            # TRIAGE.md where the owner can argue with it. An untouched document tracks the
            # shipped template, so the paragraph reaches existing installs that way.
            # a report reading itself against its own brief. Deliberately the LAST thing added to
            # the instructions: it is about this one source, so it must not be able to argue with
            # TRIAGE.md's definitions of task/reply_only/fyi - only to say what "off" looks like.
            if watch:
                system += ('\n\nTHIS IS A SCHEDULED REPORT, and the owner wrote down why they run it and what '
                           'they are watching for:\n' + str(watch)[:1200] +
                           '\nJudge the run AGAINST THAT. Something in the data matching what they are watching '
                           'for is a task - say what you saw, in the reason, using the report\'s own numbers or '
                           'names. Nothing matching is fyi, however interesting the rest of it is: a report that '
                           'becomes work every time it runs is a report nobody reads. A reply is never right here '
                           '- nobody sent this and there is nobody to answer.')
            if playbooks:
                system += ('\n\nPLAYBOOKS - the owner has written down how these kinds of job are done here, each with '
                           'the arrival that starts it (when). If this message is plainly an instance of one, add '
                           '"playbook": "<slug>" to your answer; it is then a task for the agent and it works it from that '
                           'playbook. A message that only mentions the same systems is not an instance - the `when` line '
                           'must fit. Otherwise leave the key out.\n' + str(playbooks)[:3000])
            if profiles:
                system += ('\n\nTHE WORKERS - the agents this install has, each with what it is for. When an agent will '
                           'start on this (kind: coding), add "profile": "<exactly one name below>" to say WHICH one. '
                           'This is a different question from kind: kind decides whether an agent works it at all, '
                           'profile decides who. Pick on the WORK the message asks for, not on who sent it. Unsure, or '
                           'none of them fits it better than the others? Leave the key out and the default worker takes '
                           'it.\n' + str(profiles)[:2000])
            if repos:
                system += ('\n\nKNOWN REPOSITORIES are listed in known_repositories (owner/name and what each is). For a task an agent '
                           'could work from a keyboard, add "repository": "<exactly one listed owner/name>" or null, '
                           '"needs_repo_choice": true|false and "repo_reason": "<one clause: what in the request points there>". '
                           'Decide from what the request is ABOUT; the sender\'s project associations in project_context are '
                           'supporting evidence, not proof that everything they write concerns that project. When two '
                           'repositories are plausible, or none fits, say null with needs_repo_choice true and the owner will choose - '
                           'never force a match because one repository happens to be configured.')
            if routing_history:
                from .routingmemory import PROMPT as _ROUTING_PROMPT
                system += _ROUTING_PROMPT
            if candidates is not None:
                system += ('\n\nTHIS IS A CHAT LINE, and same_day_lines are the lines of this room from the SAME calendar day, '
                           'oldest first, each with its id and the task it belongs to (null = none yet). Add to your answer '
                           '"relationship": "new" | "continues" | "answers" | "uncertain", "related_message_ids": [<ids of the '
                           'lines it continues or answers>] and "existing_task_id": <that task id, or null>. continues = it '
                           'carries on, finishes, corrects, narrows or adds detail to an ask in those lines (people type in '
                           'fragments); answers = it replies to something asked in them; new = it turns to a different subject, '
                           'however politely ("Also...", "one more thing", "separately") - two problems in one app are two jobs; '
                           'uncertain = you cannot tell. Only ids from same_day_lines count; anything older is a new subject by '
                           'rule, whatever it resembles, and a room is not a topic.')
            if project:
                system += ('\n\nPROJECT RELATIONSHIP CONTEXT - selected from the owner\'s prior explicit repository '
                           'choices for this sender/channel. It helps identify what the message is about; it does '
                           'not make an informational message a task and it is never permission to write or send. '
                           'A tentative or ambiguous relationship must not be presented as certain.')
            how = addressed_to_you(msg, mine)
            user = json.dumps({'from': msg.get('from_email'), 'subject': msg.get('subject'),
                               **({'addressed_to_you': how,
                                   'recipients': len(msg.get('to') or []) + len(msg.get('cc') or [])} if how else {}),
                               **(thread or {}),
                               **({'project_context': project} if project else {}),
                               **({'routing_history': routing_history} if routing_history else {}),
                               **({'same_day_lines': [{k: c.get(k) for k in ('id', 'who', 'when', 'text', 'task_id')} for c in candidates]} if candidates is not None else {}),
                               # 160 cut every real description mid-clause - taskuary lost "do the work, you approve", FanApp
                               # lost the noun its whole sentence was about. This is the one line the model routes on.
                               **({'known_repositories': [{'repo': r.get('repo'), 'about': (r.get('about') or '')[:REPO_ABOUT]} for r in repos]} if repos else {}),
                               **({'body_truncated': True} if len(strip_boilerplate(str(msg.get('body') or ''))) > BODY_BUDGET else {}),
                               'body': strip_boilerplate(str(msg.get('body') or ''))[:BODY_BUDGET]})
            if len(strip_boilerplate(str(msg.get('body') or ''))) > BODY_BUDGET:
                system += ('\n\nbody_truncated: the message was longer than the context budget and its end was cut. '
                           'If the verdict could depend on what you did not see, say so in your reason.')
            if images:
                system += ('\n\nImages from the message are attached. They are part of the ask - a '
                           'screenshot of the error IS the request. Read them before deciding.')
            out = llm(system, user, images=images) if images else llm(system, user)
            raw_answer = str(out or '')
            j = json.loads(re.sub(r'^```(json)?|```$', '', raw_answer.strip(), flags=re.M))
            if j.get('intent') in ('task', 'reply_only', 'fyi'):
                # `kind` is the model's SECOND verdict and it ROUTES the task to one of three
                # places: coding starts an agent, general opens the assistant's chat, task goes on
                # the owner's own list with nothing working it (ingest.auto_code_ok gates the
                # first and asks nothing about the other two). It used to be a regex over the body
                # (routing.draft_task_fields), which is how a Teams line about someone's job scope
                # opened a coding session; the model has read the whole message and TRIAGE.md's
                # definition, so its word wins when given, and the regex is only the fallback.
                out = {'intent': j['intent'], 'why': str(j.get('why') or '')[:240]}
                if j['intent'] == 'task' and j.get('kind') in ('coding', 'general', 'task'): out['kind'] = j['kind']
                # a playbook the menu actually offered rides on the task as ITS PROCEDURE; it says how the job
                # is done here, not who does it - the kind stays the model's own (PW-205: the old override to
                # coding sent a PTO request, a general job, into a checkout)
                pb = str(j.get('playbook') or '').strip().lower()
                if playbooks and pb and out['intent'] == 'task' and re.search(rf'^- {re.escape(pb)}: ', playbooks, re.M):
                    out['playbook'] = pb
                # WHICH WORKER, when one starts: validated against the roster it was actually shown, the
                # same way the playbook is. A name nobody offered is dropped, and the task falls to the
                # default profile - a hallucinated worker must not route work anywhere.
                pr = str(j.get('profile') or '').strip().lower()
                if profiles and pr and out['intent'] == 'task' and re.search(rf'^- {re.escape(pr)}: ', profiles, re.M):
                    out['profile'] = pr
                if candidates is not None: out.update(relationship_of(j, candidates))
                if repos and out['intent'] == 'task': out.update(repo_choice_of(j, repos))
                if out['intent'] == 'task':
                    # the work, named (PW-074): a title and summary of what was asked and the distinct
                    # outcomes as a list - validated, never trusted; the router falls back when absent
                    title = ' '.join(str(j.get('title') or '').split())[:120]
                    summary = str(j.get('summary') or '').strip()[:1000]
                    if title: out['title'] = title
                    if summary: out['summary'] = summary
                    if isinstance(j.get('checklist'), list): out['checklist'] = [x for x in j['checklist'] if isinstance(x, str)]
                return out
            parse_error = f"invalid intent {j.get('intent')!r}; expected task, reply_only, or fyi"
        except Exception as e:
            parse_error = f'{type(e).__name__}: {e}'
    # An LLM was supplied, answered, and the answer was not usable (bad JSON, an intent outside
    # the contract). That is NOT "no AI configured": heuristic_intent's last branch assumes real
    # work and reads none of the owner's standing notes, so a garbled answer opened a task the
    # owner had already refused - repeatedly, since every retry garbled the same way. Say the
    # verdict is degraded and let the caller file instead of guessing.
    out = heuristic_intent(msg, mine)
    if not llm:
        return out
    # A CLI can emit a whole transcript if an output flag changes. Preserve enough to diagnose
    # the contract failure without letting one response overwhelm SQLite or the Triage tab.
    raw = raw_answer or ''
    if len(raw) > 8000:
        raw = raw[:8000] + '\n… [triage output truncated at 8,000 characters]'
    return {**out, 'degraded': True, 'raw_output': raw,
            'parse_error': (parse_error or 'the response was not a usable verdict')[:1000]}


# ── one chat, several jobs ───────────────────────────────────────────────────────────────
# A chat room is not a topic. Mail threads itself - a reply carries the References header and
# belongs to what came before it by construction - but teams:<chat> and whatsapp:<jid> are a
# ROOM, and everything anyone ever says in it shares one id. Routing read that id as "the same
# thread" (routing.WEIGHTS: thread=1.0 clears the attach bar alone), so eleven lines from one
# person over an hour - four different problems and a screenshot - became ONE task carrying one
# prompt, and an agent sent at it only ever saw the first ask (owner, 2026-09-02).
#
# Nothing mechanical can split that. A gap in minutes cannot tell "let me rephrase that" from
# "Also, separate thing:", and neither can a keyword - "also" opens both. What CAN tell is a
# reader, so the reader decides, on the one question that matters, with the exchange in front of
# it: the lines they sent AND the answers we sent back, in order, because a reply of ours is the
# clearest boundary there is.
