import puppeteer from "puppeteer-core";
const b = await puppeteer.launch({ executablePath: "C:/Program Files (x86)/Microsoft/Edge/Application/msedge.exe", headless: "new" });
const p = await b.newPage();
await p.setViewport({ width: 1440, height: 900 });
await p.goto(process.argv[2], { waitUntil: "networkidle0" });
await p.evaluate(() => [...document.querySelectorAll("div")].find((d) => d.childElementCount === 0 && d.textContent === "Connectors")?.click());
await new Promise((r) => setTimeout(r, 1200));
await p.evaluate(() => [...document.querySelectorAll("p,div")].find((d) => d.textContent === "Microsoft SQL Server" && d.childElementCount === 0)?.click());
await new Promise((r) => setTimeout(r, 1200));
await p.screenshot({ path: new URL("./mssql.png", import.meta.url) });
await b.close();
console.log("ok");
